### PR TITLE
Finish setting up project (milestone 1)

### PR DESCRIPTION
**Pull request by AlfredoElizarraras**
This pull request contains:
- [x] Create a new React web app with the create react app tool.
- [x] Add Proptypes package.
- [x] Add Big js package.
- [x] Early deployment to Heroku.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required :heavy_multiplication_x: 
Great job adding the correct dependencies for this project.
Let's fix some issues before we proceed to the next milestone.

### REQUIRED
* unnecessary files or assets, such as the React svg Logo, are deleted.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/files-removed.png) from pathwright). Let's delete the React svg logo found in `src/logo.svg`.

**After making the changes, submit another request for review.**

**Happy Coding :technologist: 
Simon Wathigo.**

**Comment by AlfredoElizarraras** [comment]
Hello @wathigo  :wave: 

**Thanks for your code review** :pray: 
I wasn't aware about the logo svg, I will delete it inmmediately :sweat_smile:

**Review by wathigo — APPROVED** [review]
### Approved :heavy_check_mark: 
All requirements for this milestone have been met.

**You may proceed to the next milestone.**

**Simon Wathigo**

**Comment by AlfredoElizarraras** [comment]
## Thanks for the approval :raised_hands: 
**I will proceed to merge this branch.** :smiley:

**Pull request merged**
